// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qzbmoquxrnichsqnolls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Ym1vcXV4cm5pY2hzcW5vbGxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODM3NjAsImV4cCI6MjA5MjU1OTc2MH0.o2wHl_jE_feQ0_J1h5nEVaoVa4tp0Mpc26z122plHew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);